script/README.md, script/example-work.yaml, script/work_creation.py
=> Feat: Added script to add work to hub cluster

pkg/controllers/apply_controller.go
=> Feat: Owner references will now be checked before manifests are applied.

pkg/controllers/apply_controller.go
Removed duplicate bool check.
I have:
n/a
=> Refactor: Removed duplicate bool check.

.github/workflows/ci.yml, Dockerfile
=> Fix: Removing needed check on ci.yml

Dockerfile
This will solve the problem regarding version for the ci e2e test.
Fixes #
I have:
=> Fix: adding version to dockerfile

pkg/controllers/apply_controller_unit_test.go
=> Test: Unit test for Reconcile work controller

pkg/controllers/apply_controller_unit_test.go
=> Test: Added ApplyUnstructured test.

tests/e2e/apply_test.go, tests/e2e/testmanifests/test-configmap2.yaml
- Updated the Apply E2E tests to follow Ginkgo BDT convention.
I have:
Local E2E testing completes with 100% success.
There are minor todos and improvements for later.
=> Refactor: E2E tests refactored and improved.

pkg/controllers/finalize_controller.go, pkg/controllers/finalize_controller_unit_test.go, pkg/controllers/manager.go, pkg/utils/test_utils.go
Added event recorder and events to the Finalizer controller.
I have:
100% on local tests.
=> Feat: Added event recorder and events to the Finalizer Controller.

pkg/controllers/manager.go, pkg/controllers/work_status_controller.go, tests/e2e/apply_test.go
Fixes #
- Added Event Recorder to the Work Status Controller
- Added event creation for reconciliation success
I have:
=> Feat: Added Event Recorder to the Work Status Controller

README.md
Adding badges and updated go version requirement.
I have:
=> Docs: Minor README update.

pkg/controllers/apply_controller_integration_test.go, pkg/controllers/work_status_controller_integration_test.go
Fixed test by wrapping an async routine in an eventual check.
I have:
Local tests run.
=> Fix: Broken integration test fix.

pkg/controllers/apply_controller_integration_test.go, pkg/utils/test_utils.go
Fixes #
#57 
I have:
- Followed the issues on the integration test.
- Used KubeVela's integrations tests as reference.
- Example: https://github.com/kubevela/kubevela/blob/master/pkg/controller/common/rollout/workloads/deployment_scale_integration_test.go
=> Test: Updated the integration test for apply_controller

tests/e2e/apply_test.go
Fixes #
I have:
- Added two tests to check controller's validity on duplicate manifests on work objects.
=> Test: Added new tests for the e2e

deploy-work-api/templates/fleet-kubeconfig.yaml, deploy-work-api/templates/fleet-work-controller.yaml
=> Fix: updating helm chart

pkg/controllers/work_status_controller_integration_test.go
Fixed a broken test caused during refactor of ClientSet.
Fixes #
I have:
Local tests successful
=> Fix: Resolved issue with broken test from clientset removal.

.github/ISSUE_TEMPLATE/bug_report.md
Added an issue template for bugs.
=> Docs: Added template for bugs.

pkg/controllers/work_status_controller_integration_test.go, tests/e2e/apply_test.go
=> Fix: Fixing eventual test failures for UT

pkg/controllers/suite_test.go
=> Fix: Fixing the failure of apiserver shutdown when running integration tests locally

Makefile, pkg/controllers/apply_controller.go, pkg/controllers/apply_controller_test.go
…moved from https://github.com/Azure/k8s-work-api/pull/88
due to not updated fork.
Fixes #
I have:
=> Fix: update the manifest conditions last update time

pkg/controllers/apply_controller.go, pkg/controllers/manager.go
=> Feat: Added Available Condition to apply_controller

pkg/controllers/apply_controller.go, tests/e2e/apply_test.go
Fixes #
I have:
- Changed the random string used by the tests to be the correct format (work name cannot start with number)
- Changed all conditions to have a correct format for conditions
=> Fix: Fixed problems on e2e test

pkg/controllers/apply_controller.go, pkg/controllers/finalize_controller.go, pkg/controllers/manager.go, pkg/controllers/work_status_controller.go
=> Feat: Adding integration function for fleet

Makefile, config/crd/multicluster.x-k8s.io_appliedworks.yaml, config/crd/multicluster.x-k8s.io_works.yaml
Fix the CRD generating scripts
Fixes #
I have:
CRDs
=> Fix: generate the full crds

pkg/controllers/apply_controller.go, pkg/controllers/apply_controller_unit_test.go, pkg/controllers/finalize_controller.go, pkg/controllers/finalize_controller_unit_test.go, pkg/controllers/work_status_controller.go, pkg/controllers/work_status_controller_unit_test.go
=> Fix: Stop reconcile

.github/pr-title-config.json, pkg/controllers/apply_controller_integration_test.go, pkg/controllers/apply_controller_test.go
=> fix: fix lint and test
